apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mypvc
  namespace: yellowfin-prod
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile-csi
  resources:
    requests:
      storage: 5Gi
