apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: keyvault-jdbc
  namespace: api
spec:
  provider: azure
  parameters:
    keyvaultName: "[USER_KEYVAULT_NAME]"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "[USER_USER_ASSIGNED_IDENTITY]"
    objects:  |
      array:
        - |
          objectName: USER
          objectAlias: JDBC_CONN_USER
          objectType: secret
        - |
          objectName: PASSWORD
          objectAlias: JDBC_CONN_PASS
          objectType: secret
        - |
          objectName: ENCRYPTED
          objectAlias: JDBC_CONN_ENCRYPTED
          objectType: secret
        - |
          objectName: JDBCURL
          objectAlias: JDBC_CONN_URL
          objectType: secret        
    tenantId: "[YOUR TENANT ID]"
  secretObjects:
  - secretName: jdbc-secret
    type: Opaque
    data:
    - objectName: USER
      key: JDBC_CONN_USER
    - objectName: PASSWORD
      key: JDBC_CONN_PASS
    - objectName: ENCRYPTED
      key: JDBC_CONN_ENCRYPTED
    - objectName: JDBCURL
      key: JDBC_CONN_URL